services:
  backend:
    build: 
      context: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_PASSWORD: ${DB_PASSWORD}
      PAYMENT_KEY: ${STRIPE_API_KEY}
  admin_prod:
    build:
      context: ./admin
      target: prod
    depends_on:
      - backend
    ports:
      - "3000:80"
    profiles: ["prod"]
  admin_dev:
    build:
      context: ./admin
      target: dev
    depends_on:
      - backend
    ports:
      - "3000:5173"
    volumes:
      - ./admin/node_modules:/app/node_modules
      - ./admin/src:/app/src
    profiles: ["dev"]
  frontend_prod:
    build:
      context: ./frontend
      target: prod
    depends_on:
      - backend
    ports:
      - "3001:80"
    profiles: ["prod"]
  frontend_dev:
    build:
      context: ./frontend
      target: dev
    depends_on:
      - backend
    ports:
      - "3001:5173"
    volumes: 
      - ./frontend/node_modules:/app/node_modules
      - ./frontend/src:/app/src
    profiles: ["dev"]
  image:
    build:
      context: ./image_server
    depends_on:
      - db
    ports:
      - "3002:8080"
    volumes:
      - ./image_server/images:/app/images
  db:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
volumes:
  postgres_data:
