services:
  backend:
    build: 
      dockerfile: backend.Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_PASSWORD: mypassword
      PAYMENT_KEY: ${STRIPE_API_KEY}
  frontend:
    build:
      dockerfile: frontend.Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:80"
    volumes:
      - ./frontend/node_modules/:/app/node_modules
  db:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
volumes:
  postgres_data:
