services:
  app:
    build: 
      dockerfile: app.Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_PASSWORD: mypassword
      PAYMENT_KEY: ${STRIPE_API_KEY}
  db:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
volumes:
  postgres_data:
