FROM golang:1.25.1-alpine3.22 AS builder
WORKDIR /usr/src/app

COPY go.mod go.sum ./

RUN go mod download

COPY config.yaml .
COPY . .

RUN go build -o application .

FROM alpine:3.22
WORKDIR /app

COPY --from=builder /usr/src/app/config.yaml .
COPY --from=builder /usr/src/app/application ./app

EXPOSE 8080

CMD ["./app"]
