openapi: 3.0.3
info:
  title: E-commerce app
  version: 1.0.0

paths:
  /auth/login:
    $ref: "./paths/auth.yaml#/~1auth~1login"
  /auth/signup:
    $ref: "./paths/auth.yaml#/~1auth~1signup"
  /auth/refresh:
    $ref: "./paths/auth.yaml#/~1auth~1refresh"
components:
  schemas:
    $ref: "./components/schemas.yaml#/"
